### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2929: character maps to <undefined>

### ISSUE THREAD

**Issue by samano99** [LearnedVector/A-Hackers-AI-Voice-Assistant#17]
![Screenshot (21)](https://user-images.githubusercontent.com/72791242/95837416-2d756300-0d73-11eb-81f9-f6b8d7f7f76f.png)

**Comment by KnifeOfDunwall** [comment]
code currently mostly only works on Linux. If you want to execute it on windows you would need to use wsl2. I also don't know why a decoder has been called. I'm currently in school but when I get home I'll look into it. Also as a friendly reminder: if you want it easier, a pretrained model of the commonvoice dataset is available for download for enhancing. You would only need to use Mimic recording studio and also add that model for training. It would be training way faster. As it is p
retrained it is unnecessary to do it again for the same dataser
