### ISSUE TITLE
 cannot reshape tensor of 0 elements

### ISSUE THREAD

**Issue by MrWD10** [LearnedVector/A-Hackers-AI-Voice-Assistant#19]
I'm getting this error in dataset.py and train.py under wakeword folder while resampling waveform.
         cannot reshape tensor of 0 elements into shape [-1, 40, 0] because the unspecified dimension size -1 can be any value and is ambiguous

 try:
            file_path = self.data.key.iloc[idx]
            waveform, sr = torchaudio.load(file_path, normalization=True)
            if sr > self.sr:
                waveform = torchaudio.transforms.Resample(sr, self.sr)(waveform)
            mfcc = self.audio_transform(waveform)
            label = self.data.label.iloc[idx]
        except Exception as e:
            print(str(e))
Any help would be appreciated.

**Comment by KnifeOfDunwall** [comment]
I also had this kind of problem. Some of the data was corrupted and the ai did not train with it but most of it was intact and it trained with no problem other than it spamming the console
