### ISSUE TITLE
torchaudio C++ extension is not available

### ISSUE THREAD

**Issue by MrWD10** [LearnedVector/A-Hackers-AI-Voice-Assistant#20]
I'm getting this error in dataset.py and train.py under wakeword folder.
 Warning (from warnings module):
          File "C:\Users\A\AppData\Local\Programs\Python\Python36\lib\site-packages\torchaudio\extension\extension.py", line 14
            warnings.warn('torchaudio C++ extension is not available.')
        UserWarning: torchaudio C++ extension is not available.
 when calling SpecAugment() under dataset.py file then it throughs error. I think it's related to torchaudio. I'm using its latest version. Any help would be appreciated.

**Comment by LearnedVector** [comment]
torchaudio doesn't work on windows without building it from source. I would suggest using wsl2

**Comment by MrWD10** [comment]
> torchaudio doesn't work on windows without building it from source. I would suggest using wsl2

**Comment by MrWD10** [comment]
@LearnedVector  can you tell me its whole procedure...? And can I implement that code to android?

**Comment by MrWD10** [comment]
> torchaudio doesn't work on windows without building it from source. I would suggest using wsl2

@LearnedVector  can you tell me how to test wakeword engine on pc.....? what changes are required in engine.py file under wakeword folder.
