### ISSUE TITLE
Getting error while running wakeword engine.py

### ISSUE THREAD

**Issue by XlentAcademy** [LearnedVector/A-Hackers-AI-Voice-Assistant#35]
![Screenshot (1122)](https://user-images.githubusercontent.com/73514278/102704940-cfe82000-42a7-11eb-8134-30c22a23a43c.png)

Please help i am not getting that why i am getting this error on running the **wakeword engine.py** python script.
I am new to use ubuntu so please help me.

Thanks...

**Comment by Tdrinker** [comment]
You need to provide where to load the model thru command line arguments.

```
python engine.py --model_file path/to/your/model.zip
```

**Comment by XlentAcademy** [comment]
Thank You.
