### ISSUE TITLE
ModuleNotFoundError: No module named 'pydub'

### ISSUE THREAD

**Issue by NoCodeAvaible** [LearnedVector/A-Hackers-AI-Voice-Assistant#46]
Hello,

I get everytime I try to start commonvoice_create_jsons.py this error:

from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'

I don't know why it occurs because I've selected the right interpreter and I've downloaded the right version of pydub.
This error just freaks me out.
Can someone please help me?

**Comment by Tdrinker** [comment]
did you install it with pip?

**Comment by MartaFelix** [comment]
i have the same problem

**Comment by Tdrinker** [comment]
Without further insight into your local setting, it is hard to know exactly what went wrong. I would double check are you using a virtual environment and did you install pydub in that virtual environment?

**Comment by MartaFelix** [comment]
I'm using Anaconda to run the jupyter notebook, and I've installed pydub library with 'pip install pydub' and still doesn´t work
