### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by Elizabeth65** [LearnedVector/A-Hackers-AI-Voice-Assistant#47]
Hi, when I run `python train.py --train_file /path/to/train/json --valid_file /path/to/valid/json --load_model_from /path/to/pretrain/speechrecognition.ckpt`, this error occurs.  Where does dataset library come from? From Pytorch? From Pytorch Lightning?

**Comment by NoCodeAvaible** [comment]
Hey,
I think you have not installed dataset yet.
For conda installation:
`conda install -c coecms dataset`

For pip installation:
`pip install dataset`

**Comment by Elizabeth65** [comment]
Hey, thanks for your help. I found that actually it is my mistake that I just copy the train.py script into my folder instead of copy the whole repository.  Actually there is a folder named neuralnet containing dataset.py file. I guess import dataset means import this dataset.py file.
