### ISSUE TITLE
Model is not being saved after first epoch

### ISSUE THREAD

**Issue by NoCodeAvaible** [LearnedVector/A-Hackers-AI-Voice-Assistant#52]
Hey guys,
is it normal that my model is not being saved after the first epoch?

**Comment by Leochoi-enai** [comment]
add --save_path (check the train.py for argument list)argument for running train.py

**Comment by Tdrinker** [comment]
yes as just @Leochoi-enai mentioned you need to add save path as a command line argument to the train.py script. Also the model is saved every time there is a best epoch seen so far. 

a sample to run train.py

```
python train.py --sample_rate 8000 --epoch 100 --batch_size 32 --eval_batch_size 1 --lr 0.1 --model_name lstm_wakeword_rpi_v5 --save_checkpoint_path ../models --train_data_json ../scripts/data/train.json --test_data_json ../scripts/data/test.json --num_workers 24 --hidden_size 32
```


Closing this issue for now.
