### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: `configure_optimizers` must include a monitor when a `ReduceLROnPlateau` scheduler is used.

### ISSUE THREAD

**Issue by BIPUL-KNOVI** [LearnedVector/A-Hackers-AI-Voice-Assistant#67]
When I try to train my own dataset with train.py  I got this error... 
![Capture](https://user-images.githubusercontent.com/87002042/124555728-0dcc2080-de55-11eb-8454-882e1a21a638.PNG)

Any suggestion, please...

**Comment by BIPUL-KNOVI** [comment]
Solved by changing monitor value none to 
monitor = 'metric_to_track'

**Comment by zacknawrocki** [comment]
@BIPUL-KNOVI  Where did you set monitor = 'metric_to_track'? I'm running into this problem, as well. You did it on a line in train.py, right?
