### ISSUE TITLE
How do i use split_commonvoice.py correctly?

### ISSUE THREAD

**Issue by DarkAssassin11** [LearnedVector/A-Hackers-AI-Voice-Assistant#7]
Most of it is clear to me but the thing i dont know is which file i should use as the --file_name argument. the rest is explained very clearly.

**Comment by Harsha19111999** [comment]
@KnifeOfDunwall Could you tell me what should be passed as the --file_name argument? I am not sure how to use it because the common voice dataset consists of tsv files and clips folder. Where should I input tsv files?

**Comment by galpachino** [comment]
I also need to know what should be input as file_name

**Comment by ELMatero6** [comment]
Dunno if this thread is defunct but I figured it out. Its the train.tsv file.
