### ISSUE TITLE
Data json?

### ISSUE THREAD

**Issue by JosephAntony1** [LearnedVector/A-Hackers-AI-Voice-Assistant#9]
Might be a dumb question but how are you supposed to format the data json? 

create a train and test json in this format...
    // make each sample is on a seperate line
    {"key": "/path/to/audio/speech.wav, "text": "this is your text"}
    {"key": "/path/to/audio/speech.wav, "text": "another text example"}

isn't a valid json since the top level doesn't have any keys so both I and python are confused lol

**Comment by KnifeOfDunwall** [comment]
It would be best if you use the create_json.py but you are right, this isn't a real json format but the ai can read it when training

**Comment by JosephAntony1** [comment]
The file under the wake word directory?

**Comment by KnifeOfDunwall** [comment]
VoiceAssistant/wakeword/scripts/create_wakeword_json.py if you want the json for the wakeword ai

**Comment by KnifeOfDunwall** [comment]
Is your question answered? If yes, i will close the issue
